set_property PACKAGE_PIN W5 [get_ports CLK]
set_property PACKAGE_PIN U16 [get_ports {LEDS[0]}]
set_property PACKAGE_PIN E19 [get_ports {LEDS[1]}]
set_property PACKAGE_PIN U19 [get_ports {LEDS[2]}]
set_property PACKAGE_PIN V19 [get_ports {LEDS[3]}]
set_property PACKAGE_PIN W18 [get_ports {LEDS[4]}]
set_property PACKAGE_PIN U15 [get_ports {LEDS[5]}]
set_property PACKAGE_PIN U14 [get_ports {LEDS[6]}]
set_property PACKAGE_PIN V14 [get_ports {LEDS[7]}]
set_property PACKAGE_PIN U18 [get_ports RST]
set_property PACKAGE_PIN V2 [get_ports {SWITCHES[0]}]
set_property PACKAGE_PIN T3 [get_ports {SWITCHES[1]}]
set_property PACKAGE_PIN T2 [get_ports {SWITCHES[2]}]
set_property PACKAGE_PIN R3 [get_ports {SWITCHES[3]}]
set_property PACKAGE_PIN W2 [get_ports {SWITCHES[4]}]
set_property PACKAGE_PIN U1 [get_ports {SWITCHES[5]}]
set_property PACKAGE_PIN T1 [get_ports {SWITCHES[6]}]
set_property PACKAGE_PIN R2 [get_ports {SWITCHES[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[7]}]


set_property PACKAGE_PIN V7 [get_ports {SEVEN_SEG_CATHODE[7]}]
set_property PACKAGE_PIN U7 [get_ports {SEVEN_SEG_CATHODE[6]}]
set_property PACKAGE_PIN V5 [get_ports {SEVEN_SEG_CATHODE[5]}]
set_property PACKAGE_PIN U5 [get_ports {SEVEN_SEG_CATHODE[4]}]
set_property PACKAGE_PIN V8 [get_ports {SEVEN_SEG_CATHODE[3]}]
set_property PACKAGE_PIN U8 [get_ports {SEVEN_SEG_CATHODE[2]}]
set_property PACKAGE_PIN W6 [get_ports {SEVEN_SEG_CATHODE[1]}]
set_property PACKAGE_PIN W7 [get_ports {SEVEN_SEG_CATHODE[0]}]

set_property PACKAGE_PIN U2 [get_ports {SEVEN_SEG_ANODE[3]}]
set_property PACKAGE_PIN U4 [get_ports {SEVEN_SEG_ANODE[2]}]
set_property PACKAGE_PIN V4 [get_ports {SEVEN_SEG_ANODE[1]}]
set_property PACKAGE_PIN W4 [get_ports {SEVEN_SEG_ANODE[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG_CATHODE[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG_CATHODE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG_CATHODE[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG_CATHODE[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG_CATHODE[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG_CATHODE[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG_CATHODE[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG_CATHODE[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG_ANODE[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG_ANODE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG_ANODE[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG_ANODE[3]}]

set_property PACKAGE_PIN W19 [get_ports INT]
set_property IOSTANDARD LVCMOS33 [get_ports INT]



set_property PACKAGE_PIN A18 [get_ports UART_TX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TX]



set_property PACKAGE_PIN J17 [get_ports {G_OUT[0]}]
set_property PACKAGE_PIN H17 [get_ports {G_OUT[1]}]
set_property PACKAGE_PIN G17 [get_ports {G_OUT[2]}]
set_property PACKAGE_PIN D17 [get_ports {G_OUT[3]}]
set_property PACKAGE_PIN N18 [get_ports {B_OUT[0]}]
set_property PACKAGE_PIN L18 [get_ports {B_OUT[1]}]
set_property PACKAGE_PIN K18 [get_ports {B_OUT[2]}]
set_property PACKAGE_PIN J18 [get_ports {B_OUT[3]}]
set_property PACKAGE_PIN P19 [get_ports HSYNC]
set_property PACKAGE_PIN R19 [get_ports VSYNC]
set_property PACKAGE_PIN G19 [get_ports {R_OUT[0]}]
set_property PACKAGE_PIN H19 [get_ports {R_OUT[1]}]
set_property PACKAGE_PIN J19 [get_ports {R_OUT[2]}]
set_property PACKAGE_PIN N19 [get_ports {R_OUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_OUT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_OUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_OUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_OUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_OUT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_OUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_OUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_OUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports HSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports {R_OUT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R_OUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R_OUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R_OUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports VSYNC]


set_property PACKAGE_PIN M18 [get_ports BUTTON_PRESS]
set_property IOSTANDARD LVCMOS33 [get_ports BUTTON_PRESS]
set_property PACKAGE_PIN P18 [get_ports CLK_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT]
set_property PACKAGE_PIN N17 [get_ports LATCH_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports LATCH_OUT]
